#!/bin/bash

# Utility Functions
loadCredentials() {
  ual tss load-credentials;
}

getPasswordOnlyNppid() {
  ual tss get-password --nppid;
}

getPasswordOnlyPpid() {
  ual tss get-password --ppid;
}

devEnv() {
  ual aws auth --nppid --role DEV-N4C_CWD-L3;
  getPasswordOnlyNppid;
}

qaEnv() {
  ual aws auth --nppid --role ADFS-QA-N4C_CWD-L4;
  getPasswordOnlyNppid;
}


stgEnv() {
  ual aws auth --ppid --role ADFS-STG-N4C_CWD-L4;
  getPasswordOnlyPpid;
}

prdEnv() {
  ual aws auth --ppid --role ADFS-PRD-N4C_CWD-L4;
  getPasswordOnlyPpid;
}

execute() {
loadCredentials;
read -p "Select `echo $'\n> '` [ 1 ] dev `echo $'\n> '` [ 2 ] qa `echo $'\n> '` [ 3 ] stg `echo $'\n> '` [ 4 ] prd `echo $'\n>> '` " envResp
  case "$envResp" in
    1) devEnv;;
    2) qaEnv;;
    3) stgEnv;;
    4) prdEnv;;
  esac
}

execute;

